name: Android build & release

on:
  push:
    branches: [ main ]

    
jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
      - uses: subosito/flutter-action@v2.4.0
        with:
          channel: "stable"
      - run: flutter --version
      - run: flutter pub get
      - run: flutter pub upgrade
      - run: flutter build apk --no-tree-shake-icons --debug
      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "build/app/outputs/flutter-apk/app-debug.apk"
          tag: v1.0.${{ github.run_number }}
